In [2]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import os
import matplotlib.cm as cm

In [7]:
df_result = pd.read_csv("C:/Users/Mahima Acharya/Documents/BCI/Data/EEG_Result/Classification/all_result.csv").drop("Unnamed: 0", axis=1, errors="ignore")
df_result = df_result[df_result["Channel Reduction"] == "No"]
df_result

,Number of Classes,Pre-Processed Algorithm,Channel Reduction,Focus,Data,FrequencyBand,X_shape,y_shape,Classifier,CV,...,Intermediate Precision,Intermediate Recall,Intermediate F1-Score,Intermediate Support,Novice Precision,Novice Recall,Novice F1-Score,Novice Support,Best Group,Best Accuracy
2,2,Baseline Correction Method,No,ElectrodePosition,CodeComprehension,AlphaBetaThetaGamma,"(1600, 4)","(1600,)",RF,Leave-One-Electrode-Out CV,...,NaN,NaN,NaN,NaN,95.81,90.62,93.04,1200.00,['FC3'],100.0
4,2,Baseline Correction Method,No,Algorithm,CodeComprehension,AlphaBetaThetaGamma,"(727, 4)","(727,)",RF,Leave-One-Algorithm-Out CV,...,NaN,NaN,NaN,NaN,95.04,88.98,91.82,996.88,['HIndex'],100.0
5,2,Baseline Correction Method,No,ElectrodePosition,CodeComprehension,AlphaBetaThetaGamma,"(1600, 4)","(1600,)",RF,Stratified10-fold CV,...,NaN,NaN,NaN,NaN,95.14,90.36,92.66,7680.00,NaN,NaN
6,2,Baseline Correction Method,No,ElectrodePosition,CodeComprehension,AlphaBetaThetaGamma,"(1600, 4)","(1600,)",XGB,Stratified10-fold CV,...,NaN,NaN,NaN,NaN,94.41,91.01,92.65,7680.00,NaN,NaN
7,2,Baseline Correction Method,No,ElectrodePosition,CodeComprehension,AlphaBetaThetaGamma,"(1600, 4)","(1600,)",XGB,Leave-One-Electrode-Out CV,...,NaN,NaN,NaN,NaN,94.43,91.02,92.55,1200.00,['F4'],100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,3,Average Common Referencing,No,Algorithm,Baseline,4to50hz,"(1072, 1)","(1072,)",RF,Leave-One-Subject-Out CV,...,34.38,17.51,21.16,1078.12,30.56,20.26,23.06,886.11,[49],100.0
248,3,Baseline Correction Method,No,Algorithm,CodeComprehension,4to50hz,"(1072, 1)","(1072,)",RF,Leave-One-Subject-Out CV,...,31.25,16.19,19.19,1078.12,28.57,21.50,23.87,911.43,[6],100.0
249,3,Average Common Referencing,No,ElectrodePosition,Baseline,4to50hz,"(2368, 1)","(2368,)",RF,Leave-One-Subject-Out CV,...,34.38,16.80,19.84,2400.00,30.56,20.14,22.58,2133.33,[49],100.0
250,3,Average Common Referencing,No,ElectrodePosition,CodeComprehension,AlphaBetaThetaGamma,"(2368, 4)","(2368,)",XGB,Leave-One-Subject-Out CV,...,35.48,13.61,16.29,2477.42,34.38,21.97,24.68,2400.00,[24],100.0
251,3,Average Common Referencing,No,Algorithm,Baseline,4to50hz,"(1072, 1)","(1072,)",SVM,Leave-One-Subject-Out CV,...,27.78,4.11,6.67,1916.67,47.06,44.01,45.39,1876.47,[71],100.0

# Binary Classification

In [8]:
df_binary = df_result[df_result["Number of Classes"] == 2]
df_binary

,Number of Classes,Pre-Processed Algorithm,Channel Reduction,Focus,Data,FrequencyBand,X_shape,y_shape,Classifier,CV,...,Intermediate Precision,Intermediate Recall,Intermediate F1-Score,Intermediate Support,Novice Precision,Novice Recall,Novice F1-Score,Novice Support,Best Group,Best Accuracy
2,2,Baseline Correction Method,No,ElectrodePosition,CodeComprehension,AlphaBetaThetaGamma,"(1600, 4)","(1600,)",RF,Leave-One-Electrode-Out CV,...,NaN,NaN,NaN,NaN,95.81,90.62,93.04,1200.00,['FC3'],100.0
4,2,Baseline Correction Method,No,Algorithm,CodeComprehension,AlphaBetaThetaGamma,"(727, 4)","(727,)",RF,Leave-One-Algorithm-Out CV,...,NaN,NaN,NaN,NaN,95.04,88.98,91.82,996.88,['HIndex'],100.0
5,2,Baseline Correction Method,No,ElectrodePosition,CodeComprehension,AlphaBetaThetaGamma,"(1600, 4)","(1600,)",RF,Stratified10-fold CV,...,NaN,NaN,NaN,NaN,95.14,90.36,92.66,7680.00,NaN,NaN
6,2,Baseline Correction Method,No,ElectrodePosition,CodeComprehension,AlphaBetaThetaGamma,"(1600, 4)","(1600,)",XGB,Stratified10-fold CV,...,NaN,NaN,NaN,NaN,94.41,91.01,92.65,7680.00,NaN,NaN
7,2,Baseline Correction Method,No,ElectrodePosition,CodeComprehension,AlphaBetaThetaGamma,"(1600, 4)","(1600,)",XGB,Leave-One-Electrode-Out CV,...,NaN,NaN,NaN,NaN,94.43,91.02,92.55,1200.00,['F4'],100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,2,Average Common Referencing,No,ElectrodePosition,Baseline,4to50hz,"(1600, 1)","(1600,)",XGB,Leave-One-Subject-Out CV,...,NaN,NaN,NaN,NaN,68.75,49.22,52.35,4800.00,[71],100.0
151,2,Baseline Correction Method,No,ElectrodePosition,CodeComprehension,4to50hz,"(1600, 1)","(1600,)",RF,Leave-One-Subject-Out CV,...,NaN,NaN,NaN,NaN,48.00,34.19,36.61,3072.00,[18],100.0
156,2,Average Common Referencing,No,ElectrodePosition,Baseline,4to50hz,"(1600, 1)","(1600,)",RF,Leave-One-Subject-Out CV,...,NaN,NaN,NaN,NaN,48.00,34.00,36.66,3072.00,[18],100.0
159,2,Baseline Correction Method,No,Algorithm,CodeComprehension,4to50hz,"(727, 1)","(727,)",RF,Leave-One-Subject-Out CV,...,NaN,NaN,NaN,NaN,40.00,33.97,36.32,1276.00,[55],100.0
160,2,Average Common Referencing,No,Algorithm,Baseline,4to50hz,"(727, 1)","(727,)",RF,Leave-One-Subject-Out CV,...,NaN,NaN,NaN,NaN,44.00,34.66,37.19,1276.00,[55],100.0

In [ ]:
def oneway_anova(df_result, cv_method, target_column):
    from scipy.stats import f_oneway

    df_anova= pd.DataFrame(columns=['CV','F-statistic', 'P-value', 'Significance'])
    for method in cv_method:
        print(f"Cv : {method}")
        df_tmp = df_result[df_result['CV'] == method] 
        value = df_tmp[target_column].unique()
        count = df_tmp[target_column].nunique()
        if count == 2:
            # Perform ANOVA
            result = f_oneway(df_tmp[df_tmp[target_column] == value[0]]['Accuracy'], 
                            df_tmp[df_tmp[target_column] == value[1]]['Accuracy'])
        elif count == 3:
            result = f_oneway(df_tmp[df_tmp[target_column] == value[0]]['Accuracy'], 
                            df_tmp[df_tmp[target_column] == value[1]]['Accuracy'],
                             df_tmp[df_tmp[target_column] == value[2]]['Accuracy'])
            
        # Extracting F-statistic and p-value
        f_statistic = result.statistic
        p_value = result.pvalue

        print("F-statistic:", f_statistic)
        print("P-value:", p_value)

        if p_value < 0.05:
            p_value_result = "Yes"
        else:
            p_value_result = "No"

        df_anova.loc[len(df_anova)]= [method, f_statistic.round(2), p_value.round(2), p_value_result]
    return df_anova

# Code Comprehension vs. Baseline

In [19]:
cv_method = {'Stratified10-fold CV','Leave-One-Subject-Out CV'}
cv_method

df_car = df_binary[df_binary['Pre-Processed Algorithm']== "Average Common Referencing"]
df_car = df_car[df_car['CV'].isin(cv_method)]

mean_by_cv = df_car.groupby(['Data', df_car['CV'] == 'Stratified10-fold CV'])['Accuracy'].mean()


mean_by_cv.round(2)

Data               CV
Baseline           False    81.54
                   True     87.62
CodeComprehension  False    83.97
                   True     88.10
Name: Accuracy, dtype: float64

In [46]:
value = df_car['Data'].nunique()
value

2

In [42]:
from scipy.stats import f_oneway
target_column = 'Data'
df_anova= pd.DataFrame(columns=['CV','F-statistic', 'P-value', 'Significance'])
for method in cv_method:
    print(f"Cv : {method}")
    df_tmp = df_car[df_car['CV'] == method] 
    value = df_car[target_column].unique()
    # Perform ANOVA
    result = f_oneway(df_tmp[df_car[target_column] == value[0]]['Accuracy'], 
                    df_tmp[df_car[target_column] == value[1]]['Accuracy'])

    # Extracting F-statistic and p-value
    f_statistic = result.statistic
    p_value = result.pvalue

    print("F-statistic:", f_statistic)
    print("P-value:", p_value)

    if p_value < 0.05:
        p_value_result = "Yes"
    else:
        p_value_result = "No"

    df_anova.loc[len(df_anova)]= [method, f_statistic.round(2), p_value.round(2), p_value_result]
df_anova

Cv : Leave-One-Subject-Out CV
F-statistic: 4.580414110995169
P-value: 0.043678986363412886
Cv : Stratified10-fold CV
F-statistic: 0.1264792696065523
P-value: 0.7254981174302846

C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\2460709523.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  result = f_oneway(df_tmp[df_car[target_column] == value[0]]['Accuracy'],
C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\2460709523.py:11: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_tmp[df_car[target_column] == value[1]]['Accuracy'])
C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\2460709523.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  result = f_oneway(df_tmp[df_car[target_column] == value[0]]['Accuracy'],
C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\2460709523.py:11: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_tmp[df_car[target_column] == value[1]]['Accuracy'])

                         CV  F-statistic  P-value Significance
0  Leave-One-Subject-Out CV         4.58     0.04          Yes
1      Stratified10-fold CV         0.13     0.73           No

# Frequency Band: Full vs. Separate

In [30]:
cv_method = {'Stratified10-fold CV','Leave-One-Subject-Out CV'}
cv_method

df_band = df_binary[df_binary['CV'].isin(cv_method)]
df_band
mean_by_cv = df_car.groupby(['FrequencyBand', df_car['CV'] == 'Stratified10-fold CV'])['Accuracy'].mean()
mean_by_cv.round(2)

FrequencyBand        CV
4to50hz              False    81.70
                     True     86.66
AlphaBetaThetaGamma  False    83.80
                     True     89.06
Name: Accuracy, dtype: float64

In [31]:
from scipy.stats import f_oneway

df_anova= pd.DataFrame(columns=['CV','F-statistic', 'P-value', 'Significance'])
for method in cv_method:
    print(f"Cv : {method}")
    df_tmp = df_car[df_car['CV'] == method] 
    # Perform ANOVA
    result = f_oneway(df_tmp[df_car['FrequencyBand'] == 'AlphaBetaThetaGamma']['Accuracy'], 
                    df_tmp[df_car['FrequencyBand'] == '4to50hz']['Accuracy'])

    # Extracting F-statistic and p-value
    f_statistic = result.statistic
    p_value = result.pvalue

    print("F-statistic:", f_statistic)
    print("P-value:", p_value)

    if p_value < 0.05:
        p_value_result = "Yes"
    else:
        p_value_result = "No"

    df_anova.loc[len(df_anova)]= [method, f_statistic.round(2), p_value.round(2), p_value_result]
df_anova

Cv : Leave-One-Subject-Out CV
F-statistic: 3.272272416036946
P-value: 0.0841477994101357
Cv : Stratified10-fold CV
F-statistic: 3.667503063346538
P-value: 0.0685741621970893

C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\1501925606.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  result = f_oneway(df_tmp[df_car['FrequencyBand'] == 'AlphaBetaThetaGamma']['Accuracy'],
C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\1501925606.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_tmp[df_car['FrequencyBand'] == '4to50hz']['Accuracy'])
C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\1501925606.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  result = f_oneway(df_tmp[df_car['FrequencyBand'] == 'AlphaBetaThetaGamma']['Accuracy'],
C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\1501925606.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_tmp[df_car['FrequencyBand'] == '4to50hz']['Accuracy'])

                         CV  F-statistic  P-value Significance
0  Leave-One-Subject-Out CV         3.27     0.08           No
1      Stratified10-fold CV         3.67     0.07           No

# Analysis: Task Vs. Channel

In [32]:
cv_method = {'Stratified10-fold CV','Leave-One-Subject-Out CV'}
cv_method

df_band = df_binary[df_binary['CV'].isin(cv_method)]
df_band
mean_by_cv = df_car.groupby(['Focus', df_car['CV'] == 'Stratified10-fold CV'])['Accuracy'].mean()
mean_by_cv.round(2)

Focus              CV
Algorithm          False    82.77
                   True     87.49
ElectrodePosition  False    82.73
                   True     88.23
Name: Accuracy, dtype: float64

In [34]:
from scipy.stats import f_oneway

df_anova= pd.DataFrame(columns=['CV','F-statistic', 'P-value', 'Significance'])
for method in cv_method:
    print(f"Cv : {method}")
    df_tmp = df_car[df_car['CV'] == method] 
    # Perform ANOVA
    result = f_oneway(df_tmp[df_car['Focus'] == 'Algorithm']['Accuracy'], 
                    df_tmp[df_car['Focus'] == 'ElectrodePosition']['Accuracy'])

    # Extracting F-statistic and p-value
    f_statistic = result.statistic
    p_value = result.pvalue

    print("F-statistic:", f_statistic)
    print("P-value:", p_value)

    if p_value < 0.05:
        p_value_result = "Yes"
    else:
        p_value_result = "No"

    df_anova.loc[len(df_anova)]= [method, f_statistic.round(2), p_value.round(2), p_value_result]
df_anova

Cv : Leave-One-Subject-Out CV
F-statistic: 0.0008855722096076632
P-value: 0.97652792018363
Cv : Stratified10-fold CV
F-statistic: 0.3013992506084068
P-value: 0.5885358857877512

C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\103290689.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  result = f_oneway(df_tmp[df_car['Focus'] == 'Algorithm']['Accuracy'],
C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\103290689.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_tmp[df_car['Focus'] == 'ElectrodePosition']['Accuracy'])
C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\103290689.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  result = f_oneway(df_tmp[df_car['Focus'] == 'Algorithm']['Accuracy'],
C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\103290689.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_tmp[df_car['Focus'] == 'ElectrodePosition']['Accuracy'])

                         CV  F-statistic  P-value Significance
0  Leave-One-Subject-Out CV          0.0     0.98           No
1      Stratified10-fold CV          0.3     0.59           No

# Model

In [35]:
cv_method = {'Stratified10-fold CV','Leave-One-Subject-Out CV'}
cv_method

df_band = df_binary[df_binary['CV'].isin(cv_method)]
df_band
mean_by_cv = df_car.groupby(['Classifier', df_car['CV'] == 'Stratified10-fold CV'])['Accuracy'].mean()
mean_by_cv.round(2)

Classifier  CV
RF          False    81.33
            True     89.11
SVM         False    83.38
            True     84.17
XGB         False    83.55
            True     90.29
Name: Accuracy, dtype: float64

In [36]:
from scipy.stats import f_oneway

df_anova= pd.DataFrame(columns=['CV','F-statistic', 'P-value', 'Significance'])
for method in cv_method:
    print(f"Cv : {method}")
    df_tmp = df_car[df_car['CV'] == method] 
    # Perform ANOVA
    result = f_oneway(df_tmp[df_car['Classifier'] == 'RF']['Accuracy'], 
                    df_tmp[df_car['Classifier'] == 'SVM']['Accuracy'],
                    df_tmp[df_car['Classifier'] == 'XGB']['Accuracy']
                    )

    # Extracting F-statistic and p-value
    f_statistic = result.statistic
    p_value = result.pvalue

    print("F-statistic:", f_statistic)
    print("P-value:", p_value)

    if p_value < 0.05:
        p_value_result = "Yes"
    else:
        p_value_result = "No"

    df_anova.loc[len(df_anova)]= [method, f_statistic.round(2), p_value.round(2), p_value_result]
df_anova

Cv : Leave-One-Subject-Out CV
F-statistic: 1.4151549022638021
P-value: 0.26511900824736145
Cv : Stratified10-fold CV
F-statistic: 23.76636671271859
P-value: 4.039922444310057e-06

C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\2243625257.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  result = f_oneway(df_tmp[df_car['Classifier'] == 'RF']['Accuracy'],
C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\2243625257.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_tmp[df_car['Classifier'] == 'SVM']['Accuracy'],
C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\2243625257.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_tmp[df_car['Classifier'] == 'XGB']['Accuracy']
C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\2243625257.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  result = f_oneway(df_tmp[df_car['Classifier'] == 'RF']['Accuracy'],
C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\2243625257.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_tmp[df_car['Classifier'] == 'SVM']['Accuracy'],
C:\Users\Mahima Acharya\AppData\Local\Temp\ipykernel_12808\2243625257.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_tmp[df_car['Classifier'] == 'XGB']['Accuracy']

                         CV  F-statistic  P-value Significance
0  Leave-One-Subject-Out CV         1.42     0.27           No
1      Stratified10-fold CV        23.77     0.00          Yes